<div class="container font-q">
    <?php
    $this->render('blog/assets');
    $entry = $this->entry;
    $title = $entry->getTitle();
    $this->headTitle()->prepend($title);
    $title = $this->escapeHtml($title);
    $url   = $this->url('phly-blog/entry', array('id' => $entry->getId()));
    $ds    = function ($ts) use ($entry) {
        $tz   = $entry->getTimezone();
        $date = new \DateTime();
        $date->setTimezone(new \DateTimeZone($tz));
        $date->setTimestamp($ts);
        return $date->format('Y-m-d H:i:s');
    };

    // @codingStandardsIgnoreStart
    foreach ($this->headTitle() as $blogTitle) {}
    // @codingStandardsIgnoreEnd

    $this->headLink(array(
        'href'  => $this->url('phly-blog/feed-atom'),
        'type'  => 'application/atom+xml',
        'rel'   => 'alternate',
        'title' => $blogTitle . ' Atom Feed',
    ));
    $this->headLink(array(
        'href'  => $this->url('phly-blog/feed-rss'),
        'type'  => 'application/rss+xml',
        'rel'   => 'alternate',
        'title' => $blogTitle . ' RSS Feed',
    ));
    ?>
  <article>
    <h2><?php echo $title ?></h2>
      <?php
      echo $entry->getBody();
      echo $entry->getExtended();
      ?>
    <footer>
      <p>
        <a href="<?php echo $this->url('blog/index') ?>">Return to entries</a>
      </p>
        <?php // echo $this->render('blog/social-media') ?>
    </footer>
    <section>
        <?php // echo $this->disqus($entry->getId(), $url, $title) ?>
    </section>
  </article>
</div>





<div class="container">
  <h1>

      <?php $this->placeholder('sidebar')->captureStart(); ?>
    <a href="<?php echo $this->url('blog/index') ?>">Return to entries</a>
      <?php $this->placeholder('sidebar')->captureEnd(); ?>
      <?php $this->placeholder('sidebar')->captureStart(); ?>
    <p class="note">
      Posted by
        <?php
        $author = printf(
            '<a href="%s">%s</a>',
            $this->escapeHtmlAttr($entry->getAuthor()->getUrl()),
            $this->escapeHtml($entry->getAuthor()->getName())
        );
        ?>
    </p>
    <p class="blog-post-meta"><?php echo $ds($entry->getCreated()) ?> by <a href="#"><?=$author?></a></p>
    <p class="blog-post-meta"><?php echo $ds($entry->getUpdated()) ?> by <a href="#"><?=$author?></a></p>
      <?php $this->placeholder('sidebar')->captureEnd(); ?>
  </h1>
</div>