<?php
$entry = $this->entry;
$ds = function ($ts) use ($entry) {
    $tz = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('Y-m-d H:i:s');
};
$url = $this->plugin('url');
$entryUrl = $url('phly-blog/entry', array('id' => $entry->getId()));
$title = $this->escapeHtml($entry->getTitle());
?>

<h2 class="blog-post-title"><a href="<?php echo $entryUrl ?>"><?php echo $title ?></a></h2>
<p class="blog-post-meta">
    <ul>
  <li>
    Written on <?php echo $ds($entry->getCreated()) ?>

  </li>
  <li>
    Last updated<?php echo $ds($entry->getUpdated()) ?>
  </li>
</ul>
</p>

<div class="container">
  <article>
      <?php echo $entry->getBody() ?>
    <footer>
      <p class="text-right">
        <a href="<?php echo $entryUrl ?>">Continue reading...</a>
      </p>
    </footer>
  </article>
</div>