<?php
//$this->layout()->single = true;
$this->render('blog/assets');

$paginatorUrl = $this->paginator_url;
$urlSubstitutionString = $this->substitution;
$basePageUrl = str_replace('-p%d', '', $paginatorUrl);
if ($urlSubstitutionString) {
    $basePageUrl = str_replace('%s', str_replace(' ', '+', $urlSubstitutionString), $basePageUrl);
}

// Set head title
$this->headTitle()->prepend($this->title);

// Add feed links
$this->headLink(array(
    'href' => rtrim(dirname($basePageUrl), '/') . '/' . basename($basePageUrl, '.html') . '-atom.xml',
    'type' => 'application/atom+xml',
    'rel' => 'alternate',
    'title' => $this->title . ' Atom Feed',
));
$this->headLink(array(
    'href' => rtrim(dirname($basePageUrl), '/') . '/' . basename($basePageUrl, '.html') . '-rss.xml',
    'type' => 'application/rss+xml',
    'rel' => 'alternate',
    'title' => $this->title . ' RSS Feed',
));
$ds    = function ($entry)  {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($entry->getCreated());
    return $date->format('Y-m-d H:i:s');
};
?>
<div class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        From the Firehose
      </h3>

      <?php foreach ($this->entries as $entry): ?>
        <div class="blog-post">
            <?php echo $this->render('blog/entry-short', array('entry' => $entry)); ?>
      </div><!-- /.blog-post -->
      <?php endforeach;?>
      <?=$this->paginationControl($this->entries, 'Sliding', 'blog/paginator', array('url' => $paginatorUrl, 'substitution' => $urlSubstitutionString,)) ?>
    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
          fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->
  </div>
</div>