<?php
if ($this->pageCount < 2) return;
$urlPattern = $this->url;
if ($this->substitution) {
    $urlPattern = str_replace('%s', str_replace(' ', '+', $this->substitution), $urlPattern);
}
$firstUrl   = str_replace('-p%d', '', $urlPattern);
?>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

    <?php // First page link
    if ($this->first && $this->first != $this->current): ?>
      <li class="page-item">
        <a class="page-link" href="<?php echo $firstUrl ?>" tabindex="-1">&lt;&lt;</a>
      </li>
    <?php else: ?>
      <li class="page-item disabled">
        <a class="page-link" href="<?php echo $firstUrl ?>" tabindex="-1">&lt;&lt;</a>
      </li>
    <?php endif; ?>

      <?php
      // Previous page
      if ($this->previous): ?>
        <li class="page-item">
          <a class="page-link" href="<?php echo (($this->previous == $this->first) ? $firstUrl : sprintf($urlPattern, $this->previous)) ?>" tabindex="-1"> &lt;</a>
        </li>
      <?php else: ?>
        <li class="page-item disabled">
          <a class="page-link" href="<?php echo (($this->previous == $this->first) ? $firstUrl : sprintf($urlPattern, $this->previous)) ?>" tabindex="-1"> &lt;</a>
        </li>
      <?php endif; ?>


      <?php
      // Numbered page links
      foreach ($this->pagesInRange as $page):
          if ($page == $this->current): ?>
            <li class="page-item active">
              <a class="page-link" href="#">
                    <?php echo $page ?>
              </a>
            </li>
          <?php elseif ($page == $this->first): ?>
            <li class="page-item"><a class="page-link" href="<?php echo $firstUrl ?>"><?php echo $page ?></a></li>
          <?php else: ?>
            <li class="page-item"><a class="page-link" href="<?php printf($urlPattern, $page) ?>"><?php echo $page ?></a></li>
          <?php endif ?>
      <?php endforeach;?>

    <?php
    // Next page link
    if ($this->next): ?>
    <li class="page-item">
      <a class="page-link" href="<?php printf($urlPattern, $this->next) ?>">&gt;</a>
    </li>
    <?php else:?>
      <li class="page-item disabled">
        <a class="page-link" href="<?php printf($urlPattern, $this->next) ?>">&gt;</a>
      </li>
    <?php endif;?>





   <?php // Last page link
    if ($this->last && $this->last !== $this->current): ?>
      <li class="page-item">
        <a class="page-link" href="<?php printf($urlPattern, $this->last) ?>">&gt;&gt;</a>
      </li>
    <?php else: ?>
    <li class="page-item disabled">
      <a class="page-link" href="<?php printf($urlPattern, $this->last) ?>">&gt;&gt;</a>
    </li>
    <?php endif; ?>
  </ul>
</nav>
