<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">

    <?= $this->headTitle('VRKANSAGARA')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/assets/images/favicon.ico') ])
        ->prependStylesheet($this->basePath('/dist/css/app.css'))
//        ->prependStylesheet($this->basePath('assets/css/app.css'))
//        ->prependStylesheet($this->basePath('assets/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
    <link rel="canonical" href="<?=$this->url('home')?>">

    <?php if (is_production_mode()): ?>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-62451902-2"></script>
      <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-62451902-2');
      </script>
    <?php endif; ?>

</head>
<body class="d-flex flex-column h-100">
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="<?=$this->url('home')?>">
        <img class='nav-logo' src="<?=$this->basePath('assets/images/favicon.ico')?>" alt="">
        Vallabh Kansagara (VRKANSAGARA)
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="<?=$this->url('home')?>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<?=$this->url('blog')?>">Blog</a>
          </li>
        </ul>
        <form  method="get" action="<?=$this->url('search')?>"  class="d-flex">
          <input  name="name" value="" id="searchAnyThing" class="form-control mr-2" type="search" placeholder="Search anything..." aria-label="Search anything...">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>


<!-- Begin page content -->
<main id="app"  class="flex-shrink-0">
    <?= $this->content ?>
</main>


<footer-component></footer-component>
<?= $this->inlineScript()
    ->prependFile($this->basePath('/dist/js/vendor.js'),'text/javascript',['defer'=>true])
    ->prependFile($this->basePath('/dist/js/manifest.js'),'text/javascript',['defer'=>true])
    ->prependFile($this->basePath('/dist/js/app.js'),'text/javascript',['defer'=>true])
?>
</body>
</html>
