<div class="container mt-5 pt-5">

  <!-- Contact Us Section -->
  <div class="container">
    <div class="row">
      <!-- Section Titile -->
      <div class="col-md-12">
        <h1>Love to Hear From You</h1>
      </div>
    </div>
    <div class="row pb-4">
      <!-- Section Titile -->
      <div class="col-md-6 mt-3">
        <p>Lets connect for better consulting.</p>

        <div>
          Address: <a href="#">Ahmedabad, Gujarat, India</a>
        </div>
        <div>
          Phone:  <a href="#">+ 91 xxxxx-xxx59</a>
        </div>

        <div>
          Website:  <a target="_blank" href="https://vrkansagara.in">https://vrkansagara.in</a>
        </div>
        <div>
          Twitter: <a target="_blank" href="https://twitter.com/vrkansagara">vrkansagara</a>
        </div>
        <div>
          Facebook: <a target="_blank" href="https://facebook.com/vrkansagara">vrkansagara</a>
        </div>
        <div>
          Github: <a target="_blank" href="https://github.com/vrkansagara">vrkansagara</a>
        </div>
      </div>
      <!-- contact form -->
      <!-- <div class="col-md-6">
          <form class="shake" role="form" method="post" id="contactForm" name="contact-form" >
              Name
              <div class="form-group ">
                <label class="control-label" for="name">Name</label>
                <input class="form-control" id="name" type="text" name="name" required data-error="Please enter your name">

              </div>
              email
              <div class="form-group ">
                <label class="control-label" for="email">Email</label>
                <input class="form-control" id="email" type="email" name="email" required data-error="Please enter your Email">

              </div>
              Subject
              <div class="form-group ">
                <label class="control-label">Subject</label>
                <input class="form-control" id="msg_subject" type="text" name="subject" required data-error="Please enter your message subject">

              </div>
              Message
              <div class="form-group ">
                  <label for="message" class="control-label">Message</label>
                  <textarea class="form-control" rows="3" id="message" name="message" required data-error="Write your message"></textarea>

              </div>
              Form Submit
              <div class="form-submit mt-5">
                  <button class="btn btn-common" type="submit" id="form-submit"><i class="material-icons mdi mdi-message-outline"></i> Send Message</button>
              </div>
          </form>
      </div> -->
    </div>
  </div>
</div>