<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<main class="flex-shrink-0">
    <div class="container">
        <h1 class="mt-5">Vallabh Kansagara</h1>
        <p class="lead"><b><em>@</em>VRKANSAGARA</b></p>
    </div>
</main>

<div class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        <li data-target="#myCarousel" data-slide-to="3" class=""></li>
        <li data-target="#myCarousel" data-slide-to="4" class=""></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/assets/images/vallabh/london-bridge.jpg" alt="" width="100%">
        </div>
        <div class="carousel-item">
            <img src="/assets/images/china-trip/001.jpg" alt="" width="100%">
        </div>
        <div class="carousel-item">
            <img src="/assets/images/china-trip/002.jpg" alt="" width="100%">
        </div>
        <div class="carousel-item">
            <img src="/assets/images/china-trip/003.jpg" alt="" width="100%">
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>